export const menuData = {
    WeekNumber: 36,
    LunchMenus: [{
            DayOfWeek: "Monday",
            Date: "5.9.2022",
            SetMenus: [{
                    Name: "Vegetarian lunch (VEGGIE BUFFET)",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Quorn in tomato and vegetable sauce\n",
                            RecipeId: 14322,
                            Diets: ["*", "A", "G", "ILM", "L", "M", "VS"],
                            Nutrients: null,
                        },
                        {
                            Name: "Whole grain organic pasta",
                            RecipeId: 5842,
                            Diets: ["*", "A", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Vegan soup  (VEGGIE BUFFET)",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                            Name: "Vegan spinach soup",
                            RecipeId: 17768,
                            Diets: ["A", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                        {
                            Name: "Roasted seeds",
                            RecipeId: 17411,
                            Diets: ["G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch I",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Tuna and shrimp sauce",
                            RecipeId: 19070,
                            Diets: ["*", "A", "G", "L"],
                            Nutrients: null,
                        },
                        {
                            Name: "Tomaatti-jogurttikastike",
                            RecipeId: 19070,
                            Diets: ["*", "M", "G", "L"],
                            Nutrients: null,
                        },
                        {
                            Name: "Täysjyväriisi",
                            RecipeId: 19070,
                            Diets: ["*", "A", "G", "L", "Veg", "M"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch II",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Meatballs",
                            RecipeId: 17076,
                            Diets: ["*", "A", "L", "M"],
                            Nutrients: null,
                        },
                        {
                            Name: "Rose pepper sauce",
                            RecipeId: 102,
                            Diets: ["*", "A", "ILM", "L"],
                            Nutrients: null,
                        },
                        {
                            Name: "Boiled potatoes",
                            RecipeId: 30,
                            Diets: ["*", "A", "G", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Salad lunch",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                        Name: "Smoked ham",
                        RecipeId: -1,
                        Diets: ["*", "G", "L", "M"],
                        Nutrients: null,
                    }, ],
                },
            ],
            Html: "",
        },
        {
            DayOfWeek: "Tuesday",
            Date: "6.9.2022",
            SetMenus: [{
                    Name: "Vegetarian lunch (VEGGIE BUFFET)",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Lingonberry jam",
                            RecipeId: -1,
                            Diets: ["G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                        {
                            Name: "Spinach crêpes",
                            RecipeId: 5920,
                            Diets: ["*", "A", "ILM"],
                            Nutrients: null,
                        },
                        {
                            Name: "Papas arrugas",
                            RecipeId: 13707,
                            Diets: ["*", "G", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Vegan soup  (VEGGIE BUFFET)",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                            Name: "Cauliflower puree soup",
                            RecipeId: 20064,
                            Diets: ["A", "G", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                        {
                            Name: "Roasted seeds",
                            RecipeId: 17411,
                            Diets: ["G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch I",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Madras Chicken and yoghurt",
                            RecipeId: 19965,
                            Diets: ["A", "G", "L", "VS"],
                            Nutrients: null,
                        },
                        {
                            Name: "Whole grain rice\n",
                            RecipeId: 90,
                            Diets: ["*", "G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                        {
                            Name: "Papas arrugas",
                            RecipeId: 13707,
                            Diets: ["*", "G", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch II",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Cretan fish stew",
                            RecipeId: 16422,
                            Diets: ["*", "A", "G", "ILM", "L", "M"],
                            Nutrients: null,
                        },
                        {
                            Name: "Brown Rice",
                            RecipeId: 16422,
                            Diets: ["*", "G", "Veg", "L", "M"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Salad lunch",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                        Name: "Smoked ham",
                        RecipeId: -1,
                        Diets: ["*", "G", "L", "M"],
                        Nutrients: null,
                    }, ],
                },
            ],
            Html: "",
        },
        {
            DayOfWeek: "Wednesday",
            Date: "7.9.2022",
            SetMenus: [{
                    Name: "Vegan lunch (VEGGIE BUFFET)",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Organic tofu and vegetables in soy sauce\n",
                            RecipeId: 14317,
                            Diets: ["*", "A", "G", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                        {
                            Name: "Whole grain rice\n",
                            RecipeId: 90,
                            Diets: ["*", "G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Vegetable  soup  (VEGGIE BUFFET)",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                            Name: "Cheese soup with herbs",
                            RecipeId: 1955,
                            Diets: ["*", "A", "G", "ILM", "L"],
                            Nutrients: null,
                        },
                        {
                            Name: "Roasted seeds",
                            RecipeId: 17411,
                            Diets: ["G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Chicken and vegetable patties",
                            RecipeId: 20117,
                            Diets: ["*", "A", "L", "M"],
                            Nutrients: null,
                        },
                        {
                            Name: "Lime and garlic yogurt sauce",
                            RecipeId: 11733,
                            Diets: ["A", "G", "ILM", "L", "VS"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Pork and root vegetables in sauce",
                            RecipeId: 5440,
                            Diets: ["*", "A", "G", "L", "M", "VS"],
                            Nutrients: null,
                        },
                        {
                            Name: "Boiled potatoes",
                            RecipeId: 30,
                            Diets: ["*", "A", "G", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Salad lunch",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                        Name: "Tuna",
                        RecipeId: -1,
                        Diets: ["A", "G", "L", "M"],
                        Nutrients: null,
                    }, ],
                },
            ],
            Html: "",
        },
        {
            DayOfWeek: "Thursday",
            Date: "8.9.2022",
            SetMenus: [{
                    Name: "Vegetarian lunch (VEGGIE BUFFET)",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Corn and quinoa patties",
                            RecipeId: 15386,
                            Diets: ["*", "A", "L", "M", "VS"],
                            Nutrients: null,
                        },
                        {
                            Name: "Tzatziki",
                            RecipeId: 158,
                            Diets: ["A", "G", "ILM", "L", "VS"],
                            Nutrients: null,
                        },
                        {
                            Name: "Boiled potatoes",
                            RecipeId: 30,
                            Diets: ["*", "A", "G", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Vegan soup  (VEGGIE BUFFET)",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                            Name: "Tomato soup",
                            RecipeId: 14167,
                            Diets: ["A", "G", "ILM", "L", "M", "Veg", "VS"],
                            Nutrients: null,
                        },
                        {
                            Name: "Roasted seeds",
                            RecipeId: 17411,
                            Diets: ["G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Sauce Bolognaise",
                            RecipeId: 20541,
                            Diets: ["*", "A", "G", "L", "M", "VS"],
                            Nutrients: null,
                        },
                        {
                            Name: "Whole grain organic pasta",
                            RecipeId: 1032,
                            Diets: ["*", "A", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                        Name: "Mediterranian saithe",
                        RecipeId: 21049,
                        Diets: ["*", "A", "G", "L", "VS"],
                        Nutrients: null,
                    }, ],
                },
                {
                    Name: "Salad lunch",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                        Name: "Tuna",
                        RecipeId: -1,
                        Diets: ["A", "G", "L", "M"],
                        Nutrients: null,
                    }, ],
                },
            ],
            Html: "",
        },
        {
            DayOfWeek: "Friday",
            Date: "9.9.2022",
            SetMenus: [{
                    Name: "Vegan lunch (VEGGIE BUFFET)",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Vegetable stew Chakalaka",
                            RecipeId: 17470,
                            Diets: ["A", "L", "M", "Veg", "VS"],
                            Nutrients: null,
                        },
                        {
                            Name: "Whole grain rice\n",
                            RecipeId: 90,
                            Diets: ["*", "G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Vegetable  soup  (VEGGIE BUFFET)",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                            Name: "Pureed carrot and cheese soup",
                            RecipeId: 1519,
                            Diets: ["*", "A", "G", "ILM", "L"],
                            Nutrients: null,
                        },
                        {
                            Name: "Roasted seeds",
                            RecipeId: 17411,
                            Diets: ["G", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                            Name: "Papas arrugas",
                            RecipeId: 13707,
                            Diets: ["*", "G", "ILM", "L", "M", "Veg"],
                            Nutrients: null,
                        },
                        {
                            Name: "Fish patties",
                            RecipeId: 11204,
                            Diets: ["*", "A", "G", "L", "M"],
                            Nutrients: null,
                        },
                        {
                            Name: "Dill sauce",
                            RecipeId: 10521,
                            Diets: ["*", "A", "ILM", "L"],
                            Nutrients: null,
                        },
                    ],
                },
                {
                    Name: "Lunch",
                    Price: "2,70 / 5,97 / 8,80 €",
                    Meals: [{
                        Name: "Chicken and noodle casserole",
                        RecipeId: 9966,
                        Diets: ["*", "A", "L"],
                        Nutrients: null,
                    }, ],
                },
                {
                    Name: "Salad lunch",
                    Price: "2,00 / 4,89 / 8,00 €",
                    Meals: [{
                        Name: "Tuna",
                        RecipeId: -1,
                        Diets: ["A", "G", "L", "M"],
                        Nutrients: null,
                    }, ],
                },
            ],
            Html: "",
        },
        {
            DayOfWeek: "Saturday",
            Date: "10.9.2022",
            SetMenus: [],
            Html: "",
        },
        {
            DayOfWeek: "Sunday",
            Date: "11.9.2022",
            SetMenus: [],
            Html: "",
        },
    ],
    RequireDietFilters: [{
            Name: "GlutenFree",
            TranslatedName: "Gluten free",
            Diet: "G",
            Selected: false,
            Inactive: false,
            AdditionalVisibleDiets: [],
        },
        {
            Name: "LactoseFree",
            TranslatedName: "Lactose free",
            Diet: "L",
            Selected: false,
            Inactive: false,
            AdditionalVisibleDiets: ["M"],
        },
        {
            Name: "LowLactose",
            TranslatedName: "Low lactose",
            Diet: "VL",
            Selected: false,
            Inactive: true,
            AdditionalVisibleDiets: ["L", "M"],
        },
        {
            Name: "NoMilk",
            TranslatedName: "Milk-free",
            Diet: "M",
            Selected: false,
            Inactive: false,
            AdditionalVisibleDiets: [],
        },
        {
            Name: "Healthy",
            TranslatedName: "Comply with Finnish nutrition recommendations",
            Diet: "*",
            Selected: false,
            Inactive: false,
            AdditionalVisibleDiets: [],
        },
        {
            Name: "Vegetarian",
            TranslatedName: "Suitable for vegans",
            Diet: "Veg",
            Selected: false,
            Inactive: false,
            AdditionalVisibleDiets: [],
        },
        {
            Name: "Co2Footprint",
            TranslatedName: "Climate-friendly",
            Diet: "ILM",
            Selected: false,
            Inactive: false,
            AdditionalVisibleDiets: [],
        },
    ],
    ExcludeDietFilters: [{
            Name: "Garlic",
            TranslatedName: "Contains fresh garlic",
            Diet: "VS",
            Selected: false,
            Inactive: false,
            AdditionalVisibleDiets: [],
        },
        {
            Name: "Allergens",
            TranslatedName: "Contains allergens",
            Diet: "A",
            Selected: false,
            Inactive: false,
            AdditionalVisibleDiets: [],
        },
    ],
    RestaurantDietFilters: [],
    LastWeekMenuStartDate: null,
    NextWeekMenuStartDate: null,
    ProductDataSheets: [],
};